version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-bikeshed
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: bike_shed
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: spring-bikeshed
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bike_shed
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysql_data:
