services:
  - type: web
    name: spring-bikeshed
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://aws.connect.psdb.cloud/bike_shed?sslMode=VERIFY_IDENTITY
      - key: SPRING_DATASOURCE_USERNAME
        value: ${DATABASE_USERNAME}
      - key: SPRING_DATASOURCE_PASSWORD
        value: ${DATABASE_PASSWORD}
